### ISSUE TITLE
Camel DefaultPackageScanClassResolver can't find @Converters in the Spring Boot fat jars

### ISSUE THREAD

**Issue by hekonsek** [camel-labs/camel-labs#97]
This is really a camel-core issue. `DefaultPackageScanClassResolver` should be able to find classes in the jars nested within the Spring Boot fat jars. Currently `DefaultPackageScanClassResolver` assumes only single level of nesting:

    if (urlPath.indexOf('!') > 0) {
      urlPath = urlPath.substring(0, urlPath.indexOf('!'));
    }

I had to comment out Pi4j from the gateway fat jar, as it failed with the following error:

```
Caused by: org.apache.camel.TypeConverterLoaderException: Failed to load type converters because of: Cannot find any type converter classes from the following packages: [com.github.camellabs.component.pi4j.converter]
	at org.apache.camel.impl.converter.AnnotationTypeConverterLoader.load(AnnotationTypeConverterLoader.java:119)
	at org.apache.camel.impl.converter.BaseTypeConverterRegistry.loadTypeConverters(BaseTypeConverterRegistry.java:544)
	at org.apache.camel.impl.converter.DefaultTypeConverter.doStart(DefaultTypeConverter.java:53)
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
	at org.apache.camel.impl.DefaultCamelContext.startService(DefaultCamelContext.java:2869)
	at org.apache.camel.impl.DefaultCamelContext.doAddService(DefaultCamelContext.java:1097)
	at org.apache.camel.impl.DefaultCamelContext.addService(DefaultCamelContext.java:1058)
	at org.apache.camel.impl.DefaultCamelContext.addService(DefaultCamelContext.java:1054)
	at org.apache.camel.impl.DefaultCamelContext.getTypeConverter(DefaultCamelContext.java:1977)
```

**Comment by hekonsek** [comment]
I removed Spring Boot from the gateway (#141), so this is a problem any longer.

**Comment by hekonsek** [comment]
Done.
